use super::{EngineError, state_based_actions::check_and_apply_sbas};
use crate::types::ability::StaticAbility;
use crate::types::card::CardType;
use crate::types::{GameState, ObjectId, PermanentState, PlayerId, Step, Zone};

/// Move a land from hand to battlefield. Special action — does not use the stack (CR 405.6d).
/// Still requires priority (CR 116.2a). ETB triggered abilities generated by the land
/// entering do go on the stack (CR 603.3).
pub fn play_land(
    mut state: GameState,
    player_id: PlayerId,
    object_id: ObjectId,
) -> Result<GameState, EngineError> {
    if state.priority_player != player_id {
        return Err(EngineError::NotYourPriority);
    }
    if state.active_player != player_id {
        return Err(EngineError::CannotCastNow);
    }
    if !state.stack.is_empty() {
        return Err(EngineError::CannotCastNow); // CR 116.2a: playing a land requires empty stack
    }
    if state.lands_played_this_turn >= 1 {
        return Err(EngineError::LandLimitReached);
    }

    {
        let hand = state
            .hands
            .get(&player_id)
            .ok_or(EngineError::CardNotFound)?;
        if !hand.contains(&object_id) {
            return Err(EngineError::CardNotInHand);
        }
        let obj = state
            .objects
            .get(&object_id)
            .ok_or(EngineError::CardNotFound)?;
        if !obj.is_land() {
            return Err(EngineError::NotALand);
        }
    }

    state.mana_checkpoint = None;
    state
        .hands
        .get_mut(&player_id)
        .unwrap()
        .retain(|&id| id != object_id);
    let definition = state.objects.get(&object_id).unwrap().definition.clone();
    let mut land_perm = PermanentState::new(&definition);
    land_perm.controller_since_turn = state.turn_number;
    state.battlefield.insert(object_id, land_perm);
    state.objects.get_mut(&object_id).unwrap().zone = Zone::Battlefield;
    state.lands_played_this_turn += 1;

    // Playing a land resets the consecutive-pass counter (an action occurred).
    state.consecutive_passes = 0;
    state.priority_player = player_id; // CR 116.3 / 117.3c: actor retains priority after special action

    // CR 603.2 / CR 702.100b: collect ETB triggers and Evolve triggers via unified dispatch.
    let etb_triggers = crate::engine::triggered::collect_triggers_for_event(
        &mut state,
        &crate::types::GameEvent::EntersTheBattlefield {
            subject_id: object_id,
        },
    );
    for t in etb_triggers {
        let id = t.id;
        state.stack.push(id);
        state.stack_objects.insert(id, t);
    }

    Ok(check_and_apply_sbas(state))
}

// CR 702.8a, CR 304.1: instants and Flash permanents may be cast at instant speed
fn is_instant_speed(obj: &crate::types::CardObject) -> bool {
    obj.definition
        .type_line
        .card_types
        .contains(&CardType::Instant)
        || obj.has_keyword(StaticAbility::Flash)
}

/// Cast any spell from hand — creatures, instants, sorceries, artifacts, enchantments.
/// Timing: instants and Flash cards need only priority (CR 702.8a).
/// All others require sorcery speed: active player, main phase, empty stack (CR 307.1).
pub fn cast_spell(
    mut state: GameState,
    player_id: PlayerId,
    object_id: ObjectId,
    declared_targets: Vec<crate::types::effect::EffectTarget>,
    x_value: Option<u32>,
) -> Result<GameState, EngineError> {
    if state.priority_player != player_id {
        return Err(EngineError::NotYourPriority);
    }

    // CR 601.2c: targets declared when spell is cast; validate count and legality.
    {
        use crate::engine::targeting::is_legal_target;
        use crate::types::OracleSpan;
        use crate::types::ability::Ability;
        let target_requirements: Vec<crate::types::ability::TargetFilter> = state
            .objects
            .get(&object_id)
            .map(|obj| {
                obj.definition
                    .abilities
                    .iter()
                    .filter_map(|span| match span {
                        OracleSpan::Parsed(Ability::SpellEffect(sa)) => {
                            Some(sa.target_requirements.clone())
                        }
                        _ => None,
                    })
                    .flatten()
                    .collect()
            })
            .unwrap_or_default();
        if target_requirements.len() != declared_targets.len() {
            return Err(EngineError::WrongNumberOfTargets);
        }
        let spell_colors: Vec<crate::types::mana::ManaColor> = state
            .objects
            .get(&object_id)
            .map(|o| o.definition.colors.clone())
            .unwrap_or_default();
        for (filter, target) in target_requirements.iter().zip(declared_targets.iter()) {
            if !is_legal_target(&state, target, filter, player_id, &spell_colors) {
                return Err(EngineError::IllegalTarget);
            }
        }
    }

    let cost = {
        let hand = state
            .hands
            .get(&player_id)
            .ok_or(EngineError::CardNotFound)?;
        if !hand.contains(&object_id) {
            return Err(EngineError::CardNotInHand);
        }
        let obj = state
            .objects
            .get(&object_id)
            .ok_or(EngineError::CardNotFound)?;

        if !is_instant_speed(obj) {
            // Sorcery-speed restrictions (CR 307.1)
            if state.active_player != player_id {
                return Err(EngineError::CannotCastNow);
            }
            if !matches!(state.step(), Step::PreCombatMain | Step::PostCombatMain) {
                return Err(EngineError::CannotCastNow);
            }
            if !state.stack.is_empty() {
                return Err(EngineError::CannotCastNow);
            }
        }

        obj.definition
            .mana_cost
            .clone()
            .ok_or(EngineError::CannotCastNow)?
    };

    use crate::types::ability::CostComponent;
    state = super::costs::pay_cost_components(
        state,
        player_id,
        &[CostComponent::Mana(cost.clone())],
        x_value,
    )?;
    state.mana_checkpoint = None;
    state
        .hands
        .get_mut(&player_id)
        .unwrap()
        .retain(|&id| id != object_id);
    {
        let obj = state.objects.get_mut(&object_id).unwrap();
        obj.zone = Zone::Stack;
    }

    let stack_id = state.alloc_stack_id();
    let stack_obj = crate::types::StackObject {
        id: stack_id,
        payload: crate::types::StackPayload::Spell { card_id: object_id },
        controller: player_id,
        targets: declared_targets,
        x_value,
    };
    state.stack.push(stack_id);
    state.stack_objects.insert(stack_id, stack_obj);

    // CR 117.3c: caster retains priority after casting
    state.consecutive_passes = 0;
    state.priority_player = player_id;

    // CR 603.2: fire SpellCast event for triggered abilities (e.g. Prowess — CR 702.108a).
    let spell_cast_triggers = crate::engine::triggered::collect_triggers_for_event(
        &mut state,
        &crate::types::GameEvent::SpellCast {
            caster: player_id,
            spell_id: object_id,
        },
    );
    for t in spell_cast_triggers {
        let id = t.id;
        state.stack.push(id);
        state.stack_objects.insert(id, t);
    }

    // CR 702.21a: if any declared target is an opponent-controlled battlefield permanent,
    // fire TargetedBy event to collect Ward triggers (Ward is now a TriggeredAbility).
    let spell_targets = state.stack_objects[&stack_id].targets.clone();
    let mut ward_triggers = Vec::new();
    for target in &spell_targets {
        if let crate::types::effect::EffectTarget::Object { id: target_id } = target
            && state
                .objects
                .get(target_id)
                .map(|o| o.controller != player_id)
                .unwrap_or(false)
            && state.battlefield.contains_key(target_id)
        {
            let mut t = super::triggered::collect_triggers_for_event(
                &mut state,
                &crate::types::GameEvent::TargetedBy {
                    target_id: *target_id,
                    acting_player: player_id,
                },
            );
            // Ward triggers must target the triggering spell so CounterSpell resolves correctly.
            for trigger in &mut t {
                trigger
                    .targets
                    .push(crate::types::effect::EffectTarget::StackObject { id: stack_id });
            }
            ward_triggers.append(&mut t);
        }
    }
    for wt in ward_triggers.into_iter().rev() {
        let id = wt.id;
        state.stack.push(id);
        state.stack_objects.insert(id, wt);
    }

    Ok(state)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cards::test_helpers::test_db;
    use crate::types::ability::StaticAbility;
    use crate::types::card::{CardDefinition, CardType, TypeLine};
    use crate::types::effect::EffectStep;
    use crate::types::mana::{ManaCost, ManaPip};
    use crate::types::{Ability, OracleSpan};
    use crate::types::{CardObject, Player, Step};

    fn make_instant_def(name: &str, cost_pips: Vec<ManaPip>) -> CardDefinition {
        use crate::types::ability::SpellAbility;
        CardDefinition {
            name: name.into(),
            mana_cost: Some(ManaCost { pips: cost_pips }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Draw a card.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![],
                steps: vec![EffectStep::DrawCard(1)],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![],
        }
    }

    fn make_flash_creature_def() -> CardDefinition {
        CardDefinition {
            name: "Flash Bear".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Generic(1), ManaPip::Blue],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Creature],
                subtypes: vec![],
            },
            oracle_text: "Flash".into(),
            abilities: vec![OracleSpan::Parsed(Ability::Static(StaticAbility::Flash))],
            text_annotations: vec![],
            power: Some(2),
            toughness: Some(2),
            colors: vec![],
        }
    }

    #[test]
    fn cast_instant_succeeds_with_nonempty_stack() {
        use crate::types::stack::{StackObject, StackPayload};
        let mut gs = make_state();
        // put a dummy object on the stack so it's non-empty
        let sid = gs.alloc_stack_id();
        gs.stack.push(sid);
        gs.stack_objects.insert(
            sid,
            StackObject {
                id: sid,
                payload: StackPayload::TriggeredAbility {
                    source_id: ObjectId(99),
                    effect: vec![],
                    label: "dummy".into(),
                },
                controller: PlayerId(0),
                targets: vec![],
                x_value: None,
            },
        );
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.blue += 1;
        let id = put_in_hand(
            &mut gs,
            PlayerId(0),
            make_instant_def("Opt", vec![ManaPip::Blue]),
        );

        let gs = cast_spell(gs, PlayerId(0), id, vec![], None).unwrap();

        assert_eq!(gs.objects[&id].zone, Zone::Stack);
    }

    #[test]
    fn cast_instant_when_not_active_player_succeeds() {
        let mut gs = make_state();
        gs.active_player = PlayerId(1); // opponent's turn
        gs.priority_player = PlayerId(0);
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.blue += 1;
        let id = put_in_hand(
            &mut gs,
            PlayerId(0),
            make_instant_def("Opt", vec![ManaPip::Blue]),
        );

        let gs = cast_spell(gs, PlayerId(0), id, vec![], None).unwrap();

        assert_eq!(gs.objects[&id].zone, Zone::Stack);
    }

    #[test]
    fn cast_flash_creature_with_nonempty_stack_succeeds() {
        use crate::types::stack::{StackObject, StackPayload};
        let mut gs = make_state();
        let sid = gs.alloc_stack_id();
        gs.stack.push(sid);
        gs.stack_objects.insert(
            sid,
            StackObject {
                id: sid,
                payload: StackPayload::TriggeredAbility {
                    source_id: ObjectId(99),
                    effect: vec![],
                    label: "dummy".into(),
                },
                controller: PlayerId(0),
                targets: vec![],
                x_value: None,
            },
        );
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.blue += 2;
        let id = put_in_hand(&mut gs, PlayerId(0), make_flash_creature_def());

        let gs = cast_spell(gs, PlayerId(0), id, vec![], None).unwrap();

        assert_eq!(gs.objects[&id].zone, Zone::Stack);
    }

    #[test]
    fn cast_creature_without_flash_fails_with_nonempty_stack() {
        use crate::types::stack::{StackObject, StackPayload};
        let db = test_db();
        let mut gs = make_state();
        let sid = gs.alloc_stack_id();
        gs.stack.push(sid);
        gs.stack_objects.insert(
            sid,
            StackObject {
                id: sid,
                payload: StackPayload::TriggeredAbility {
                    source_id: ObjectId(99),
                    effect: vec![],
                    label: "dummy".into(),
                },
                controller: PlayerId(0),
                targets: vec![],
                x_value: None,
            },
        );
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        assert!(matches!(
            cast_spell(gs, PlayerId(0), id, vec![], None),
            Err(EngineError::CannotCastNow)
        ));
    }

    #[test]
    fn cast_spell_moves_card_to_stack() {
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_spell(gs, PlayerId(0), id, vec![], None).unwrap();

        assert!(!gs.hands[&PlayerId(0)].contains(&id));
        assert_eq!(gs.objects[&id].zone, Zone::Stack);
        assert_eq!(gs.stack.len(), 1);
    }

    #[test]
    fn cast_spell_caster_retains_priority() {
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_spell(gs, PlayerId(0), id, vec![], None).unwrap();

        assert_eq!(gs.priority_player, PlayerId(0));
        assert_eq!(gs.consecutive_passes, 0);
    }

    fn make_state() -> GameState {
        let mut gs = GameState::new(vec![
            Player::new(PlayerId(0), "Alice"),
            Player::new(PlayerId(1), "Bob"),
        ]);
        gs.step = Step::PreCombatMain;
        gs
    }

    fn put_in_hand(
        state: &mut GameState,
        owner: PlayerId,
        def: crate::types::CardDefinition,
    ) -> ObjectId {
        let id = state.alloc_id();
        let obj = CardObject::new(id, def, owner, Zone::Hand);
        state.hands.get_mut(&owner).unwrap().push(id);
        state.add_object(obj);
        id
    }

    #[test]
    fn play_land_moves_from_hand_to_battlefield() {
        let db = test_db();
        let mut gs = make_state();
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        let gs = play_land(gs, PlayerId(0), forest_id).unwrap();

        assert!(!gs.hands[&PlayerId(0)].contains(&forest_id));
        assert!(gs.battlefield.contains_key(&forest_id));
        assert_eq!(gs.objects[&forest_id].zone, Zone::Battlefield);
        assert_eq!(gs.lands_played_this_turn, 1);
    }

    #[test]
    fn cannot_play_second_land_in_same_turn() {
        let db = test_db();
        let mut gs = make_state();
        gs.lands_played_this_turn = 1;
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        assert!(matches!(
            play_land(gs, PlayerId(0), forest_id),
            Err(EngineError::LandLimitReached)
        ));
    }

    #[test]
    fn cannot_cast_creature_without_mana() {
        let db = test_db();
        let mut gs = make_state();
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        assert!(matches!(
            cast_spell(gs, PlayerId(0), bear_id, vec![], None),
            Err(EngineError::InsufficientMana)
        ));
    }

    #[test]
    fn cast_creature_clears_mana_checkpoint() {
        let db = test_db();
        let mut gs = make_state();
        // Give player enough mana and a checkpoint.
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        // Create a minimal checkpoint manually to simulate a prior tap.
        gs.mana_checkpoint = Some(crate::types::ManaCheckpoint {
            pools: std::collections::HashMap::new(),
            tapped_lands: vec![],
        });
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_spell(gs, PlayerId(0), bear_id, vec![], None).unwrap();

        assert!(gs.mana_checkpoint.is_none());
    }

    #[test]
    fn play_land_clears_mana_checkpoint() {
        let db = test_db();
        let mut gs = make_state();
        gs.mana_checkpoint = Some(crate::types::ManaCheckpoint {
            pools: std::collections::HashMap::new(),
            tapped_lands: vec![],
        });
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        let gs = play_land(gs, PlayerId(0), forest_id).unwrap();

        assert!(gs.mana_checkpoint.is_none());
    }

    #[test]
    fn cast_creature_puts_spell_on_stack_not_battlefield() {
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_spell(gs, PlayerId(0), bear_id, vec![], None).unwrap();

        assert!(!gs.battlefield.contains_key(&bear_id));
        assert!(gs.hands[&PlayerId(0)].is_empty());
        assert_eq!(gs.objects[&bear_id].zone, Zone::Stack);
        assert_eq!(gs.stack.len(), 1);
    }

    #[test]
    fn cast_creature_caster_retains_priority() {
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_spell(gs, PlayerId(0), bear_id, vec![], None).unwrap();

        // CR 117.3c: caster retains priority
        assert_eq!(gs.priority_player, PlayerId(0));
        assert_eq!(gs.consecutive_passes, 0);
    }

    #[test]
    fn cast_creature_not_your_priority_returns_error() {
        let db = test_db();
        let mut gs = make_state();
        gs.priority_player = PlayerId(1); // opponent has priority
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        assert!(matches!(
            cast_spell(gs, PlayerId(0), bear_id, vec![], None),
            Err(EngineError::NotYourPriority)
        ));
    }

    #[test]
    fn cast_creature_resolves_to_battlefield_after_both_pass() {
        use crate::engine::stack::pass_priority;
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_spell(gs, PlayerId(0), bear_id, vec![], None).unwrap();
        let gs = pass_priority(gs, PlayerId(0)).unwrap();
        let gs = pass_priority(gs, PlayerId(1)).unwrap();

        assert!(gs.battlefield.contains_key(&bear_id));
        assert!(gs.stack.is_empty());
    }

    #[test]
    fn play_land_not_your_priority_returns_error() {
        let db = test_db();
        let mut gs = make_state();
        gs.priority_player = PlayerId(1); // opponent has priority
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        assert!(matches!(
            play_land(gs, PlayerId(0), forest_id),
            Err(EngineError::NotYourPriority)
        ));
    }

    #[test]
    fn cast_noncreature_with_prowess_creature_puts_boost_on_stack() {
        use crate::engine::triggered::prowess_triggered_ability;
        use crate::types::ability::Ability;
        use crate::types::card::{CardDefinition, CardType, TypeLine};
        use crate::types::mana::ManaPip;
        use crate::types::{CardObject, OracleSpan, PermanentState, Zone};

        let mut gs = make_state();
        // Prowess creature (as TriggeredAbility) on battlefield.
        let prowess_def = CardDefinition {
            name: "Monk".into(),
            mana_cost: None,
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Creature],
                subtypes: vec![],
            },
            oracle_text: String::new(),
            abilities: vec![OracleSpan::Parsed(Ability::Triggered(
                prowess_triggered_ability(),
            ))],
            text_annotations: vec![],
            power: Some(1),
            toughness: Some(1),
            colors: vec![],
        };
        let monk_id = gs.alloc_id();
        let obj = CardObject::new(monk_id, prowess_def, PlayerId(0), Zone::Battlefield);
        let mut perm = PermanentState::new(&obj.definition);
        perm.controller_since_turn = 0;
        gs.battlefield.insert(monk_id, perm);
        gs.add_object(obj);

        // Cast an instant.
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.blue += 1;
        let spell_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            make_instant_def("Opt", vec![ManaPip::Blue]),
        );
        let gs = cast_spell(gs, PlayerId(0), spell_id, vec![], None).unwrap();

        // Spell on stack + 1 Prowess trigger on stack = 2 items.
        assert_eq!(gs.stack.len(), 2);
    }

    #[test]
    fn cast_targeted_spell_without_target_returns_wrong_number() {
        use crate::types::ability::{SpellAbility, TargetFilter};
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 1;
        let targeted_instant_def = CardDefinition {
            name: "Giant Growth".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Green],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Target creature gets +3/+3 until end of turn.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![TargetFilter::Creature],
                steps: vec![],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![],
        };
        let id = put_in_hand(&mut gs, PlayerId(0), targeted_instant_def);
        let result = cast_spell(gs, PlayerId(0), id, vec![], None);
        assert!(matches!(result, Err(EngineError::WrongNumberOfTargets)));
    }

    #[test]
    fn cast_targeted_spell_with_illegal_target_returns_illegal_target() {
        use crate::types::ability::{SpellAbility, TargetFilter};
        use crate::types::effect::EffectTarget;
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 1;
        let targeted_instant_def = CardDefinition {
            name: "Giant Growth".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Green],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Target creature gets +3/+3 until end of turn.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![TargetFilter::Creature],
                steps: vec![],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![],
        };
        let id = put_in_hand(&mut gs, PlayerId(0), targeted_instant_def);
        // ObjectId(999) doesn't exist
        let result = cast_spell(
            gs,
            PlayerId(0),
            id,
            vec![EffectTarget::Object { id: ObjectId(999) }],
            None,
        );
        assert!(matches!(result, Err(EngineError::IllegalTarget)));
    }

    #[test]
    fn cast_targeted_spell_with_valid_target_succeeds() {
        use crate::types::PermanentState;
        use crate::types::ability::{SpellAbility, TargetFilter};
        use crate::types::effect::EffectTarget;
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 1;
        // Place a creature on the battlefield
        let creature_def = CardDefinition {
            name: "Bear".into(),
            mana_cost: None,
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Creature],
                subtypes: vec![],
            },
            oracle_text: String::new(),
            abilities: vec![],
            text_annotations: vec![],
            power: Some(2),
            toughness: Some(2),
            colors: vec![],
        };
        let creature_id = gs.alloc_id();
        let obj = CardObject::new(creature_id, creature_def, PlayerId(1), Zone::Battlefield);
        gs.battlefield
            .insert(creature_id, PermanentState::new(&obj.definition));
        gs.add_object(obj);

        let targeted_instant_def = CardDefinition {
            name: "Giant Growth".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Green],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Target creature gets +3/+3 until end of turn.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![TargetFilter::Creature],
                steps: vec![],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![],
        };
        let id = put_in_hand(&mut gs, PlayerId(0), targeted_instant_def);
        let gs = cast_spell(
            gs,
            PlayerId(0),
            id,
            vec![EffectTarget::Object { id: creature_id }],
            None,
        )
        .unwrap();
        assert_eq!(gs.objects[&id].zone, Zone::Stack);
        // targets stored on stack object
        let stack_id = gs.stack[0];
        assert_eq!(
            gs.stack_objects[&stack_id].targets,
            vec![EffectTarget::Object { id: creature_id }]
        );
    }

    #[test]
    fn cast_untargeted_spell_with_no_targets_still_works() {
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.blue += 1;
        let id = put_in_hand(
            &mut gs,
            PlayerId(0),
            make_instant_def("Opt", vec![ManaPip::Blue]),
        );
        let gs = cast_spell(gs, PlayerId(0), id, vec![], None).unwrap();
        assert_eq!(gs.objects[&id].zone, Zone::Stack);
    }

    #[test]
    fn play_land_fails_with_nonempty_stack() {
        use crate::types::stack::{StackObject, StackPayload};
        let db = test_db();
        let mut gs = make_state();
        // Put a dummy trigger on the stack to make it non-empty
        let sid = gs.alloc_stack_id();
        let obj = StackObject {
            id: sid,
            payload: StackPayload::TriggeredAbility {
                source_id: crate::types::ObjectId(99),
                effect: vec![],
                label: "dummy".into(),
            },
            controller: PlayerId(0),
            targets: vec![],
            x_value: None,
        };
        gs.stack.push(sid);
        gs.stack_objects.insert(sid, obj);

        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        assert!(matches!(
            play_land(gs, PlayerId(0), forest_id),
            Err(EngineError::CannotCastNow)
        ));
    }

    // --- CR 702.21a Ward trigger tests ---

    fn make_ward_creature_def(ward_cost: Vec<ManaPip>) -> CardDefinition {
        use crate::types::ability::{
            CostComponent, TriggerEvent, TriggerTargetMode, TriggeredAbility, TurnOwner,
        };
        use crate::types::effect::EffectStep;
        let cost = vec![CostComponent::Mana(ManaCost { pips: ward_cost })];
        CardDefinition {
            name: "Ward Bear".into(),
            mana_cost: None,
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Creature],
                subtypes: vec![],
            },
            oracle_text: "Ward {2}".into(),
            abilities: vec![OracleSpan::Parsed(Ability::Triggered(TriggeredAbility {
                trigger: TriggerEvent::TargetedBy {
                    controller: TurnOwner::Opponent,
                },
                condition: None,
                target_mode: TriggerTargetMode::None,
                effect: vec![EffectStep::Payment {
                    cost,
                    on_paid: vec![],
                    on_declined: vec![EffectStep::CounterSpell],
                }],
            }))],
            text_annotations: vec![],
            power: Some(2),
            toughness: Some(2),
            colors: vec![],
        }
    }

    fn make_targeted_instant_def() -> CardDefinition {
        use crate::types::ability::{SpellAbility, TargetFilter};
        CardDefinition {
            name: "Shock".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Red],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Target creature gets -1/-1 until end of turn.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![TargetFilter::Creature],
                steps: vec![],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![],
        }
    }

    /// CR 702.21a: Targeting an opponent's Ward permanent while casting a spell should push a
    /// TriggeredAbility with a Payment effect above the spell on the stack.
    #[test]
    fn ward_trigger_pushed_above_spell_when_targeting_opponent_ward_creature() {
        use crate::types::ability::CostComponent;
        use crate::types::effect::{EffectStep, EffectTarget};
        use crate::types::stack::StackPayload;
        use crate::types::{CardObject, PermanentState};

        let mut gs = make_state();
        // Opponent (PlayerId(1)) has a creature with Ward({2}) on the battlefield.
        let ward_def = make_ward_creature_def(vec![ManaPip::Generic(2)]);
        let ward_id = gs.alloc_id();
        let ward_obj = CardObject::new(ward_id, ward_def, PlayerId(1), Zone::Battlefield);
        gs.battlefield
            .insert(ward_id, PermanentState::new(&ward_obj.definition));
        gs.add_object(ward_obj);

        // Caster (PlayerId(0)) casts a targeted instant at the Ward creature.
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.red += 1;
        let spell_id = put_in_hand(&mut gs, PlayerId(0), make_targeted_instant_def());
        let gs = cast_spell(
            gs,
            PlayerId(0),
            spell_id,
            vec![EffectTarget::Object { id: ward_id }],
            None,
        )
        .unwrap();

        // Stack should have: [bottom] spell, [top] TriggeredAbility (Ward).
        assert_eq!(gs.stack.len(), 2);
        let spell_stack_id = gs.stack[0];
        let ward_trigger_stack_id = gs.stack[1];

        // Bottom of stack is the spell.
        assert!(matches!(
            gs.stack_objects[&spell_stack_id].payload,
            StackPayload::Spell { .. }
        ));
        // Top of stack is a TriggeredAbility with a Payment step targeting the spell.
        match &gs.stack_objects[&ward_trigger_stack_id].payload {
            StackPayload::TriggeredAbility { effect, .. } => {
                assert_eq!(effect.len(), 1);
                match &effect[0] {
                    EffectStep::Payment {
                        cost, on_declined, ..
                    } => {
                        assert_eq!(
                            *cost,
                            vec![CostComponent::Mana(ManaCost {
                                pips: vec![ManaPip::Generic(2)]
                            })]
                        );
                        assert!(matches!(on_declined[0], EffectStep::CounterSpell));
                    }
                    other => panic!("Expected Payment step, got {other:?}"),
                }
            }
            other => panic!("Expected TriggeredAbility, got {other:?}"),
        }
        // Ward trigger targets the triggering spell.
        assert_eq!(
            gs.stack_objects[&ward_trigger_stack_id].targets,
            vec![EffectTarget::StackObject { id: spell_stack_id }]
        );
        // TriggeredAbility is controlled by the Ward permanent's controller (CR 603.3a).
        assert_eq!(
            gs.stack_objects[&ward_trigger_stack_id].controller,
            PlayerId(1)
        );
    }

    /// CR 702.21a: Ward does NOT trigger when targeting your own permanent.
    #[test]
    fn ward_trigger_not_pushed_when_targeting_own_ward_creature() {
        use crate::types::effect::EffectTarget;
        use crate::types::{CardObject, PermanentState};

        let mut gs = make_state();
        // Caster (PlayerId(0)) has a creature with WardMana({2}) — targeting own permanent.
        let ward_def = make_ward_creature_def(vec![ManaPip::Generic(2)]);
        let ward_id = gs.alloc_id();
        let ward_obj = CardObject::new(ward_id, ward_def, PlayerId(0), Zone::Battlefield);
        gs.battlefield
            .insert(ward_id, PermanentState::new(&ward_obj.definition));
        gs.add_object(ward_obj);

        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.red += 1;
        let spell_id = put_in_hand(&mut gs, PlayerId(0), make_targeted_instant_def());
        let gs = cast_spell(
            gs,
            PlayerId(0),
            spell_id,
            vec![EffectTarget::Object { id: ward_id }],
            None,
        )
        .unwrap();

        // Only the spell on the stack — no Ward trigger.
        assert_eq!(gs.stack.len(), 1);
    }

    /// CR 702.21a: Ward life triggers correctly.
    #[test]
    fn ward_life_trigger_pushed_above_spell() {
        use crate::types::ability::CostComponent;
        use crate::types::effect::{EffectStep, EffectTarget};
        use crate::types::stack::StackPayload;
        use crate::types::{CardObject, PermanentState};

        let mut gs = make_state();
        // Opponent has a creature with Ward—Pay 3 life.
        use crate::types::ability::{TriggerEvent, TriggerTargetMode, TriggeredAbility, TurnOwner};
        let ward_def = CardDefinition {
            name: "Ward Life Bear".into(),
            mana_cost: None,
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Creature],
                subtypes: vec![],
            },
            oracle_text: "Ward\u{2014}Pay 3 life.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::Triggered(TriggeredAbility {
                trigger: TriggerEvent::TargetedBy {
                    controller: TurnOwner::Opponent,
                },
                condition: None,
                target_mode: TriggerTargetMode::None,
                effect: vec![EffectStep::Payment {
                    cost: vec![CostComponent::PayLife(3)],
                    on_paid: vec![],
                    on_declined: vec![EffectStep::CounterSpell],
                }],
            }))],
            text_annotations: vec![],
            power: Some(2),
            toughness: Some(2),
            colors: vec![],
        };
        let ward_id = gs.alloc_id();
        let ward_obj = CardObject::new(ward_id, ward_def, PlayerId(1), Zone::Battlefield);
        gs.battlefield
            .insert(ward_id, PermanentState::new(&ward_obj.definition));
        gs.add_object(ward_obj);

        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.red += 1;
        let spell_id = put_in_hand(&mut gs, PlayerId(0), make_targeted_instant_def());
        let gs = cast_spell(
            gs,
            PlayerId(0),
            spell_id,
            vec![EffectTarget::Object { id: ward_id }],
            None,
        )
        .unwrap();

        assert_eq!(gs.stack.len(), 2);
        let ward_trigger_stack_id = gs.stack[1];
        match &gs.stack_objects[&ward_trigger_stack_id].payload {
            StackPayload::TriggeredAbility { effect, .. } => {
                assert_eq!(effect.len(), 1);
                match &effect[0] {
                    EffectStep::Payment { cost, .. } => {
                        assert_eq!(*cost, vec![CostComponent::PayLife(3)]);
                    }
                    other => panic!("Expected Payment step, got {other:?}"),
                }
            }
            other => panic!("Expected TriggeredAbility, got {other:?}"),
        }
    }

    #[test]
    fn cast_spell_with_x_deducts_x_mana() {
        use crate::types::mana::ManaPip;
        let mut gs = GameState::new(vec![
            Player::new(PlayerId(0), "Alice"),
            Player::new(PlayerId(1), "Bob"),
        ]);
        gs.step = Step::PreCombatMain;
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.red = 4;
        let id = gs.alloc_id();
        let def = make_instant_def("Fireball", vec![ManaPip::X, ManaPip::Red]);
        let obj = CardObject::new(id, def, PlayerId(0), crate::types::Zone::Hand);
        gs.add_object(obj);
        gs.hands.entry(PlayerId(0)).or_default().push(id);
        gs.priority_player = PlayerId(0);

        let gs = cast_spell(gs, PlayerId(0), id, vec![], Some(3)).unwrap();
        // X=3 + R=1 = 4 red spent
        assert_eq!(gs.get_player(PlayerId(0)).unwrap().mana_pool.red, 0);
    }

    // CR 107.4: X is fixed when the spell is cast and must be available at resolution.
    #[test]
    fn cast_spell_with_x_stores_x_value_on_stack_object() {
        use crate::types::mana::ManaPip;
        let mut gs = GameState::new(vec![
            Player::new(PlayerId(0), "Alice"),
            Player::new(PlayerId(1), "Bob"),
        ]);
        gs.step = Step::PreCombatMain;
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.red = 4;
        let id = gs.alloc_id();
        let def = make_instant_def("Fireball", vec![ManaPip::X, ManaPip::Red]);
        let obj = CardObject::new(id, def, PlayerId(0), crate::types::Zone::Hand);
        gs.add_object(obj);
        gs.hands.entry(PlayerId(0)).or_default().push(id);
        gs.priority_player = PlayerId(0);

        let gs = cast_spell(gs, PlayerId(0), id, vec![], Some(3)).unwrap();
        let stack_id = *gs.stack.last().unwrap();
        assert_eq!(gs.stack_objects[&stack_id].x_value, Some(3));
    }

    // --- Counterspell integration tests (CR 701.5, CR 608.2b) ---

    fn make_counterspell_def() -> CardDefinition {
        use crate::types::ability::{SpellAbility, SpellFilter, TargetFilter};
        use crate::types::mana::ManaColor;
        CardDefinition {
            name: "Counterspell".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Blue, ManaPip::Blue],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Counter target spell.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![TargetFilter::Spell(SpellFilter::any())],
                steps: vec![EffectStep::CounterSpell],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![ManaColor::Blue],
        }
    }

    fn make_negate_def() -> CardDefinition {
        use crate::types::ability::{SpellAbility, SpellFilter, TargetFilter};
        use crate::types::mana::ManaColor;
        CardDefinition {
            name: "Negate".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Generic(1), ManaPip::Blue],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Counter target noncreature spell.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![TargetFilter::Spell(SpellFilter::noncreature())],
                steps: vec![EffectStep::CounterSpell],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![ManaColor::Blue],
        }
    }

    /// P0 casts Grizzly Bears; P0 passes; P1 counters with Counterspell; both pass → Bears countered.
    #[test]
    fn counterspell_counters_opponent_creature_spell() {
        use crate::engine::stack::pass_priority;
        use crate::types::effect::EffectTarget;

        let db = test_db();
        let mut gs = make_state();

        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bears_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );
        let gs = cast_spell(gs, PlayerId(0), bears_id, vec![], None).unwrap();
        let bears_sid = gs.stack[0];

        let mut gs = pass_priority(gs, PlayerId(0)).unwrap();

        gs.get_player_mut(PlayerId(1)).unwrap().mana_pool.blue += 2;
        let counter_id = put_in_hand(&mut gs, PlayerId(1), make_counterspell_def());
        let gs = cast_spell(
            gs,
            PlayerId(1),
            counter_id,
            vec![EffectTarget::StackObject { id: bears_sid }],
            None,
        )
        .unwrap();

        // P1 retains priority; P1 passes, P0 passes → resolve Counterspell.
        let gs = pass_priority(gs, PlayerId(1)).unwrap();
        let gs = pass_priority(gs, PlayerId(0)).unwrap();

        assert!(!gs.battlefield.contains_key(&bears_id));
        assert_eq!(gs.objects[&bears_id].zone, Zone::Graveyard);
        assert!(gs.graveyards[&PlayerId(0)].contains(&bears_id));
        assert_eq!(gs.objects[&counter_id].zone, Zone::Graveyard);
        assert!(gs.stack.is_empty());
    }

    /// P0 casts an instant (noncreature); P0 passes; P1 counters with Negate; both pass → instant countered.
    #[test]
    fn negate_counters_opponent_noncreature_spell() {
        use crate::engine::stack::pass_priority;
        use crate::types::ability::SpellAbility;
        use crate::types::effect::EffectTarget;
        use crate::types::mana::ManaColor;

        let mut gs = make_state();

        let draw_def = CardDefinition {
            name: "Opt".into(),
            mana_cost: Some(ManaCost {
                pips: vec![ManaPip::Blue],
            }),
            type_line: TypeLine {
                supertypes: vec![],
                card_types: vec![CardType::Instant],
                subtypes: vec![],
            },
            oracle_text: "Draw a card.".into(),
            abilities: vec![OracleSpan::Parsed(Ability::SpellEffect(SpellAbility {
                target_requirements: vec![],
                steps: vec![EffectStep::DrawCard(1)],
            }))],
            text_annotations: vec![],
            power: None,
            toughness: None,
            colors: vec![ManaColor::Blue],
        };
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.blue += 1;
        let draw_id = put_in_hand(&mut gs, PlayerId(0), draw_def);
        let gs = cast_spell(gs, PlayerId(0), draw_id, vec![], None).unwrap();
        let draw_sid = gs.stack[0];

        let mut gs = pass_priority(gs, PlayerId(0)).unwrap();

        gs.get_player_mut(PlayerId(1)).unwrap().mana_pool.blue += 2;
        let negate_id = put_in_hand(&mut gs, PlayerId(1), make_negate_def());
        let gs = cast_spell(
            gs,
            PlayerId(1),
            negate_id,
            vec![EffectTarget::StackObject { id: draw_sid }],
            None,
        )
        .unwrap();

        let gs = pass_priority(gs, PlayerId(1)).unwrap();
        let gs = pass_priority(gs, PlayerId(0)).unwrap();

        assert_eq!(gs.objects[&draw_id].zone, Zone::Graveyard);
        assert!(gs.graveyards[&PlayerId(0)].contains(&draw_id));
        assert!(gs.stack.is_empty());
    }

    /// P1 tries to Negate P0's Grizzly Bears (a creature spell) → IllegalTarget.
    #[test]
    fn negate_cannot_target_creature_spell() {
        use crate::engine::stack::pass_priority;
        use crate::types::effect::EffectTarget;

        let db = test_db();
        let mut gs = make_state();

        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bears_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );
        let gs = cast_spell(gs, PlayerId(0), bears_id, vec![], None).unwrap();
        let bears_sid = gs.stack[0];

        let mut gs = pass_priority(gs, PlayerId(0)).unwrap();

        gs.get_player_mut(PlayerId(1)).unwrap().mana_pool.blue += 2;
        let negate_id = put_in_hand(&mut gs, PlayerId(1), make_negate_def());
        let result = cast_spell(
            gs,
            PlayerId(1),
            negate_id,
            vec![EffectTarget::StackObject { id: bears_sid }],
            None,
        );

        assert!(matches!(result, Err(EngineError::IllegalTarget)));
    }

    /// P0's Counterspell fizzles when its Bears target is already countered before resolution.
    /// CR 608.2b: if all targets are illegal at resolution, the spell is countered.
    #[test]
    fn counterspell_fizzles_when_target_already_gone() {
        use crate::engine::stack::{counter_spell_on_stack, pass_priority};
        use crate::types::effect::EffectTarget;

        let db = test_db();
        let mut gs = make_state();

        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bears_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );
        let gs = cast_spell(gs, PlayerId(0), bears_id, vec![], None).unwrap();
        let bears_sid = gs.stack[0];

        let mut gs = pass_priority(gs, PlayerId(0)).unwrap();

        gs.get_player_mut(PlayerId(1)).unwrap().mana_pool.blue += 2;
        let counter_id = put_in_hand(&mut gs, PlayerId(1), make_counterspell_def());
        let gs = cast_spell(
            gs,
            PlayerId(1),
            counter_id,
            vec![EffectTarget::StackObject { id: bears_sid }],
            None,
        )
        .unwrap();

        // P1 passes, then Bears are removed from the stack before resolution.
        let mut gs = pass_priority(gs, PlayerId(1)).unwrap();
        counter_spell_on_stack(&mut gs, bears_sid);

        // P0 passes → Counterspell resolves but fizzles (target gone — CR 608.2b).
        let gs = pass_priority(gs, PlayerId(0)).unwrap();

        // Counterspell fizzled to graveyard without effect.
        assert_eq!(gs.objects[&counter_id].zone, Zone::Graveyard);
        // Bears already countered; in graveyard.
        assert_eq!(gs.objects[&bears_id].zone, Zone::Graveyard);
        assert!(gs.stack.is_empty());
    }
}
