use super::{
    EngineError,
    mana::{greedy_payment_plan, pay_mana_cost},
    state_based_actions::check_and_apply_sbas,
};
use crate::types::{GameState, ObjectId, PlayerId, Zone};

/// Move a land from hand to battlefield. Special action — does not use the stack (CR 405.6d).
/// Still requires priority (CR 116.2a). ETB triggered abilities generated by the land
/// entering do go on the stack (CR 603.3).
pub fn play_land(
    mut state: GameState,
    player_id: PlayerId,
    object_id: ObjectId,
) -> Result<GameState, EngineError> {
    if state.priority_player != player_id {
        return Err(EngineError::NotYourPriority);
    }
    if state.active_player != player_id {
        return Err(EngineError::CannotCastNow);
    }
    if !state.stack.is_empty() {
        return Err(EngineError::CannotCastNow); // CR 116.2a: playing a land requires empty stack
    }
    if state.lands_played_this_turn >= 1 {
        return Err(EngineError::LandLimitReached);
    }

    {
        let hand = state
            .hands
            .get(&player_id)
            .ok_or(EngineError::CardNotFound)?;
        if !hand.contains(&object_id) {
            return Err(EngineError::CardNotInHand);
        }
        let obj = state
            .objects
            .get(&object_id)
            .ok_or(EngineError::CardNotFound)?;
        if !obj.is_land() {
            return Err(EngineError::NotALand);
        }
    }

    state.mana_checkpoint = None;
    state
        .hands
        .get_mut(&player_id)
        .unwrap()
        .retain(|&id| id != object_id);
    state.battlefield.push(object_id);
    {
        let obj = state.objects.get_mut(&object_id).unwrap();
        obj.zone = Zone::Battlefield;
        obj.summoning_sick = false;
    }
    state.lands_played_this_turn += 1;

    // Playing a land resets the consecutive-pass counter (an action occurred).
    state.consecutive_passes = 0;
    state.priority_player = player_id; // CR 116.3 / 117.3c: actor retains priority after special action

    // Collect any ETB triggers from the land entering and push onto stack.
    let triggers = crate::engine::triggered::collect_etb_triggers(&mut state, object_id);
    for trigger in triggers {
        let id = trigger.id;
        state.stack.push(id);
        state.stack_objects.insert(id, trigger);
    }

    Ok(check_and_apply_sbas(state))
}

/// Cast a creature from hand. Sorcery speed: active player's main phase, empty stack (CR 307).
/// The spell goes on the stack; it resolves when all players pass in succession (CR 405.5).
pub fn cast_creature(
    mut state: GameState,
    player_id: PlayerId,
    object_id: ObjectId,
) -> Result<GameState, EngineError> {
    if state.priority_player != player_id {
        return Err(EngineError::NotYourPriority);
    }
    if state.active_player != player_id {
        return Err(EngineError::CannotCastNow);
    }
    if !state.stack.is_empty() {
        return Err(EngineError::CannotCastNow);
    }

    let cost = {
        let hand = state
            .hands
            .get(&player_id)
            .ok_or(EngineError::CardNotFound)?;
        if !hand.contains(&object_id) {
            return Err(EngineError::CardNotInHand);
        }
        let obj = state
            .objects
            .get(&object_id)
            .ok_or(EngineError::CardNotFound)?;
        if !obj.is_creature() {
            return Err(EngineError::NotACreature);
        }
        obj.definition
            .mana_cost
            .clone()
            .ok_or(EngineError::CannotCastNow)?
    };

    let plan = {
        let player = state
            .get_player(player_id)
            .ok_or(EngineError::CardNotFound)?;
        greedy_payment_plan(&cost, &player.mana_pool, player.life)
            .ok_or(EngineError::InsufficientMana)?
    };
    state = pay_mana_cost(state, player_id, &cost, &plan)?;
    state.mana_checkpoint = None;
    state
        .hands
        .get_mut(&player_id)
        .unwrap()
        .retain(|&id| id != object_id);
    {
        let obj = state.objects.get_mut(&object_id).unwrap();
        obj.zone = Zone::Stack;
    }

    let stack_id = state.alloc_stack_id();
    let stack_obj = crate::types::StackObject {
        id: stack_id,
        payload: crate::types::StackPayload::Spell { card_id: object_id },
        controller: player_id,
    };
    state.stack.push(stack_id);
    state.stack_objects.insert(stack_id, stack_obj);

    // CR 117.3c: caster retains priority after casting
    state.consecutive_passes = 0;
    state.priority_player = player_id;

    Ok(state)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cards::test_helpers::test_db;
    use crate::types::{CardObject, Player, Step};

    fn make_state() -> GameState {
        let mut gs = GameState::new(vec![
            Player::new(PlayerId(0), "Alice"),
            Player::new(PlayerId(1), "Bob"),
        ]);
        gs.step = Step::PreCombatMain;
        gs
    }

    fn put_in_hand(
        state: &mut GameState,
        owner: PlayerId,
        def: crate::types::CardDefinition,
    ) -> ObjectId {
        let id = state.alloc_id();
        let obj = CardObject::new(id, def, owner, Zone::Hand);
        state.hands.get_mut(&owner).unwrap().push(id);
        state.add_object(obj);
        id
    }

    #[test]
    fn play_land_moves_from_hand_to_battlefield() {
        let db = test_db();
        let mut gs = make_state();
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        let gs = play_land(gs, PlayerId(0), forest_id).unwrap();

        assert!(!gs.hands[&PlayerId(0)].contains(&forest_id));
        assert!(gs.battlefield.contains(&forest_id));
        assert_eq!(gs.objects[&forest_id].zone, Zone::Battlefield);
        assert_eq!(gs.lands_played_this_turn, 1);
    }

    #[test]
    fn cannot_play_second_land_in_same_turn() {
        let db = test_db();
        let mut gs = make_state();
        gs.lands_played_this_turn = 1;
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        assert!(matches!(
            play_land(gs, PlayerId(0), forest_id),
            Err(EngineError::LandLimitReached)
        ));
    }

    #[test]
    fn cannot_cast_creature_without_mana() {
        let db = test_db();
        let mut gs = make_state();
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        assert!(matches!(
            cast_creature(gs, PlayerId(0), bear_id),
            Err(EngineError::InsufficientMana)
        ));
    }

    #[test]
    fn cast_creature_clears_mana_checkpoint() {
        let db = test_db();
        let mut gs = make_state();
        // Give player enough mana and a checkpoint.
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        // Create a minimal checkpoint manually to simulate a prior tap.
        gs.mana_checkpoint = Some(crate::types::ManaCheckpoint {
            pools: std::collections::HashMap::new(),
            tapped_lands: vec![],
        });
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_creature(gs, PlayerId(0), bear_id).unwrap();

        assert!(gs.mana_checkpoint.is_none());
    }

    #[test]
    fn play_land_clears_mana_checkpoint() {
        let db = test_db();
        let mut gs = make_state();
        gs.mana_checkpoint = Some(crate::types::ManaCheckpoint {
            pools: std::collections::HashMap::new(),
            tapped_lands: vec![],
        });
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        let gs = play_land(gs, PlayerId(0), forest_id).unwrap();

        assert!(gs.mana_checkpoint.is_none());
    }

    #[test]
    fn cast_creature_puts_spell_on_stack_not_battlefield() {
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_creature(gs, PlayerId(0), bear_id).unwrap();

        assert!(!gs.battlefield.contains(&bear_id));
        assert!(gs.hands[&PlayerId(0)].is_empty());
        assert_eq!(gs.objects[&bear_id].zone, Zone::Stack);
        assert_eq!(gs.stack.len(), 1);
    }

    #[test]
    fn cast_creature_caster_retains_priority() {
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_creature(gs, PlayerId(0), bear_id).unwrap();

        // CR 117.3c: caster retains priority
        assert_eq!(gs.priority_player, PlayerId(0));
        assert_eq!(gs.consecutive_passes, 0);
    }

    #[test]
    fn cast_creature_not_your_priority_returns_error() {
        let db = test_db();
        let mut gs = make_state();
        gs.priority_player = PlayerId(1); // opponent has priority
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        assert!(matches!(
            cast_creature(gs, PlayerId(0), bear_id),
            Err(EngineError::NotYourPriority)
        ));
    }

    #[test]
    fn cast_creature_resolves_to_battlefield_after_both_pass() {
        use crate::engine::stack::pass_priority;
        let db = test_db();
        let mut gs = make_state();
        gs.get_player_mut(PlayerId(0)).unwrap().mana_pool.green += 2;
        let bear_id = put_in_hand(
            &mut gs,
            PlayerId(0),
            db.get("Grizzly Bears").unwrap().clone(),
        );

        let gs = cast_creature(gs, PlayerId(0), bear_id).unwrap();
        let gs = pass_priority(gs, PlayerId(0)).unwrap();
        let gs = pass_priority(gs, PlayerId(1)).unwrap();

        assert!(gs.battlefield.contains(&bear_id));
        assert!(gs.stack.is_empty());
    }

    #[test]
    fn play_land_not_your_priority_returns_error() {
        let db = test_db();
        let mut gs = make_state();
        gs.priority_player = PlayerId(1); // opponent has priority
        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        assert!(matches!(
            play_land(gs, PlayerId(0), forest_id),
            Err(EngineError::NotYourPriority)
        ));
    }

    #[test]
    fn play_land_fails_with_nonempty_stack() {
        use crate::types::stack::{StackId, StackObject, StackPayload};
        let db = test_db();
        let mut gs = make_state();
        // Put a dummy trigger on the stack to make it non-empty
        let sid = gs.alloc_stack_id();
        let obj = StackObject {
            id: sid,
            payload: StackPayload::TriggeredAbility {
                source_id: crate::types::ObjectId(99),
                effect: vec![],
                label: "dummy".into(),
            },
            controller: PlayerId(0),
        };
        gs.stack.push(sid);
        gs.stack_objects.insert(sid, obj);

        let forest_id = put_in_hand(&mut gs, PlayerId(0), db.get("Forest").unwrap().clone());

        assert!(matches!(
            play_land(gs, PlayerId(0), forest_id),
            Err(EngineError::CannotCastNow)
        ));
    }
}
